# Generated by Django 4.0 on 2021-12-23 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 12, 23, 16, 21, 24, 964457, tzinfo=utc)),
        ),
    ]
